# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd725f0b95c76d5c296f1fbf42533650b8612ea8055b4ab10359daf02b7eabadb7fa4b07aba3908de6381f171534f875ef216f0bebc15b36b88a5e8d3158823

test:
  secret_key_base: e2f485027b477d88b41c01a6ea3b91c39ede104d8243d6f6608eaa8401da48863fcacd5ff5021f92669448f7ce509624dc5867126b7d24134f0e2dc685ce494d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
